# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoOcxAgPdid33GFs7TKwZ1RVlqjYWSdK
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Charger les données
url = 'https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv'
cars_df = pd.read_csv(url)

# Application Streamlit
st.title('Analyse des Données des Voitures')

# Sélectionner la région avec des boutons radio
st.sidebar.header('Filtrer par Région')
continent = st.sidebar.radio(
    'Sélectionner une région',
    ['Tous', 'US', 'Europe', 'Japon']
)

if continent != 'Tous':
    cars_df = cars_df[cars_df['continent'] == continent]

# Afficher les statistiques de base
st.subheader('Statistiques de Base')
st.write(cars_df.describe())

# Graphique de distribution
st.subheader('Distribution des Variables')
fig, axes = plt.subplots(3, 3, figsize=(18, 12))
fig.tight_layout(pad=5.0)

# Histogrammes pour chaque variable numérique
for i, col in enumerate(['mpg', 'cylinders', 'cubicinches', 'hp', 'weightlbs', 'time-to-60']):
    sns.histplot(cars_df[col], kde=True, ax=axes[i // 3, i % 3])
    axes[i // 3, i % 3].set_title(f'Distribution de {col}')
    axes[i // 3, i % 3].set_xlabel('')
    axes[i // 3, i % 3].set_ylabel('')

st.pyplot(fig)

# Matrice de corrélation
st.subheader('Matrice de Corrélation')
corr = cars_df[['mpg', 'cylinders', 'cubicinches', 'hp', 'weightlbs', 'time-to-60']].corr()
fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', ax=ax)
st.pyplot(fig)
