# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoOcxAgPdid33GFs7TKwZ1RVlqjYWSdK
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import streamlit as st

# Charger les données
@st.cache
def load_data():
    url = 'https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv'
    df = pd.read_csv(url)
    return df

df = load_data()

# Interface utilisateur pour filtrer par région
region = st.sidebar.selectbox('Choisir une région:', ['US', 'Europe', 'Japon'])
df_filtered = df[df['region'] == region]

# Afficher les premiers enregistrements
st.write(f'Données pour la région : {region}')
st.dataframe(df_filtered.head())

# Analyse de distribution
st.subheader('Distribution des Variables')
st.write('Distribution des prix des voitures')
fig_price_dist = px.histogram(df_filtered, x='price', title='Distribution des Prix des Voitures')
st.plotly_chart(fig_price_dist)

# Analyse de corrélation
st.subheader('Analyse de Corrélation')
corr = df_filtered.corr()
st.write('Matrice de Corrélation')
st.dataframe(corr)
fig_corr_heatmap = px.imshow(corr, title='Matrice de Corrélation')
st.plotly_chart(fig_corr_heatmap)

# Graphiques supplémentaires (Exemple : Relation entre le prix et la puissance)
st.subheader('Relation entre Prix et Puissance')
fig_price_power = px.scatter(df_filtered, x='power', y='price', title='Prix vs Puissance')
st.plotly_chart(fig_price_power)